-- Contrario Command Center v4 — Seed data
-- Run AFTER schema.sql. Idempotent: re-running clears + reinserts.

begin;

truncate candidates, roles, clients, knowledge_base, kpi_entries, daily_reviews, tasks, sheet_syncs, imports restart identity cascade;

-- ── Seed clients ────────────────────────────────────
insert into clients (name, status, ats, slack_channel) values
  ('AfterQuery', 'active', 'Contrario', '#afterquery-contrario'),
  ('Alinea Invest', 'active', 'Contrario', '#alinea-contrario'),
  ('Amari AI', 'active', 'Contrario', '#amari-contrario'),
  ('Antes AI', 'active', 'Contrario', null),
  ('Aravalli Capital', 'active', 'Contrario', null),
  ('AthenaHQ', 'active', 'Ashby', '#athenahq-contrario'),
  ('BACH', 'active', 'Contrario', null),
  ('Bespoke Labs', 'active', 'Ashby', '#bespokelabs-contrario'),
  ('Besty AI', 'active', 'Contrario', '#bestyai-contrario'),
  ('Bluejay', 'active', 'Contrario', '#bluejay-contrario'),
  ('Cardinal', 'active', 'Contrario', '#cardinal-contrario'),
  ('CollectWise', 'active', 'Contrario', null),
  ('Colonist', 'active', 'Contrario', null),
  ('Contrario', 'active', 'Contrario', null),
  ('Convexia', 'active', 'Contrario', null),
  ('DoDo Inc.', 'active', 'Contrario', null),
  ('Dots (YC S21)', 'active', 'Contrario', '#dots-contrario'),
  ('Dynamo AI', 'active', 'Contrario', null),
  ('foam', 'active', 'Contrario', '#foam-contrario'),
  ('Gallium', 'active', 'Contrario', null),
  ('Gigi', 'active', 'Contrario', '#gigi-contrario'),
  ('Innate Inc.', 'active', 'Contrario', null),
  ('Jampack AI', 'active', 'Ashby', null),
  ('Judgment Labs', 'active', 'Contrario', '#judgmentlabs-contrario'),
  ('Known', 'active', 'Ashby', null),
  ('Kobalt Labs', 'active', 'Contrario', '#kobaltlabs-contrario'),
  ('Liquid', 'active', 'Contrario', null),
  ('Listen Labs', 'active', 'Ashby', '#listenlabs-contrario'),
  ('Loop AI', 'active', 'Contrario', null),
  ('Mason AI', 'active', 'Calendly', null),
  ('Maximor AI', 'active', 'Contrario', null),
  ('Mem0', 'active', 'Contrario', '#mem0-contrario'),
  ('Mixed Nuts Inc.', 'active', 'Contrario', null),
  ('Porter', 'active', 'Contrario', '#porter-contrario'),
  ('Remy AI', 'active', 'Calendly', null),
  ('Sieve', 'active', 'Contrario', '#sieve-contrario'),
  ('Simula', 'active', 'Contrario', '#simula-contrario'),
  ('Soff (YC)', 'active', 'Contrario', '#soff-contrario'),
  ('Sphinx Labs', 'active', 'Contrario', '#sphinx-contrario'),
  ('Strala', 'active', 'Contrario', '#strala-contrario'),
  ('Trellis AI', 'active', 'Contrario', '#trellis-contrario'),
  ('TriFetch', 'active', 'Contrario', '#trifetch-contrario'),
  ('Uncountable', 'active', 'Contrario', null),
  ('Verita AI', 'active', 'Contrario', '#veritaai-contrario'),
  ('VRChat', 'active', 'Lever', '#vrchat-contrario'),
  ('Wildcard', 'active', 'Calendly', null),
  ('Wispr AI', 'active', 'Contrario', null)
on conflict do nothing;

-- ── Seed roles (88 JDs from Lucía's actual data) ────
-- Status mapping: Active → 'live', Complete → 'filled'
insert into roles (client_id, title, type, location, compensation, yoe, bounty, status)
select (select id from clients where name = c), r, t::text, l, cm, y, b, s::text
from (values
  ('AfterQuery', 'Technical Account Manager', 'GTM', 'SF (in-person)', 'TBD', 'TBD', '15%', 'live'),
  ('AfterQuery', 'Tech GTM Associate / GTM Lead', 'GTM', 'SF (in-person)', 'TBD', 'TBD', '15%', 'live'),
  ('AfterQuery', 'Growth Associate', 'GTM', 'SF (in-person)', 'TBD', 'TBD', '14%', 'live'),
  ('AfterQuery', 'Research Scientist', 'Data / ML', 'SF (in-person)', 'TBD', 'TBD', '15%', 'live'),
  ('AfterQuery', 'Sr Software Engineer, Infra & Platform', 'Engineering', 'SF (in-person)', '$220K-$280K / $500K-$1M equity (4yr)', '5+', '15%', 'live'),
  ('AfterQuery', 'Software Engineer, Platform & Research', 'Engineering', 'SF (in-person)', 'TBD', '3-6', '15%', 'live'),
  ('AfterQuery', 'Strategic Projects Lead', 'Ops', 'SF (in-person)', 'TBD', 'TBD', '15%', 'live'),
  ('Alinea Invest', 'Software Engineer, Reliability & Platform', 'Engineering', 'Remote US / NYC preferred', '$170K-$220K', '3-7', 'TBD', 'live'),
  ('Alinea Invest', 'iOS Product Engineer, LATAM', 'Engineering', 'Remote LATAM', '$8K-$10K/mo', '3+', 'TBD', 'live'),
  ('Alinea Invest', 'Founding AI Engineer', 'Engineering', 'NYC (in-person)', '$160K-$200K', 'Any', 'TBD', 'live'),
  ('Amari AI', 'Full Stack Engineer', 'Engineering', 'SF (in-person)', 'Up to high $200s / 0.2%-0.5% equity', '4+', '25%', 'live'),
  ('Amari AI', 'Senior Frontend Engineer', 'Engineering', 'SF (in-person)', '$170K-$220K + equity', 'TBD', '18.5%', 'live'),
  ('Antes AI', 'Applied AI Engineer', 'Engineering', 'SF (in-person)', '$180K-$250K / 0.1%-1% equity', 'TBD', 'TBD', 'live'),
  ('Aravalli Capital', 'AI Systems Engineer', 'Engineering', 'SF (in-person)', 'TBD', 'TBD', 'TBD', 'live'),
  ('AthenaHQ', 'Account Executive', 'Sales', 'SF (in-person)', '$120K-$150K base / $240K-$300K OTE', '2-5', '15.5%', 'live'),
  ('AthenaHQ', 'Product Engineer', 'Engineering', 'SF (in-person)', '$140K-$200K', '0-5', '17.5%', 'live'),
  ('BACH', 'Account Executive', 'Sales', 'SF (in-person)', '$65K-$75K base / up to $171K OTE', 'TBD', '15.5%', 'live'),
  ('Bespoke Labs', 'Strategic Projects Lead', 'Ops', 'Bangalore / Mountain View', '$40K-$60K (India) / $160K-$300K (US)', '1-3', '15.5%', 'live'),
  ('Bespoke Labs', 'Senior DevOps Engineer (Contract)', 'Engineering', 'Remote worldwide', '$600-$1K/deliverable / $10K-$50K total', '2-15', '20% of contract', 'live'),
  ('Besty AI', 'Operations & Strategy Lead', 'Ops', 'TBD', 'TBD', 'TBD', 'TBD', 'filled'),
  ('Besty AI', 'Head of Finance & Operations', 'Ops', 'NYC (in-person)', '$150K-$200K / 0.3%-0.5% equity', '4+', 'TBD', 'live'),
  ('Bluejay', 'Senior Founding Engineer', 'Engineering', 'SF (in-person)', '$200K-$250K / 0.20%-1.00% equity', 'TBD', 'TBD', 'live'),
  ('Bluejay', 'Founding GTM', 'GTM', 'SF (in-person)', '$120K-$220K + 8-15% commission', 'TBD', 'TBD', 'live'),
  ('Cardinal', 'Founding Sales', 'Sales', 'SF (in-person)', '$100K-$140K base / $200K-$280K OTE', '2-5', '15.5%', 'live'),
  ('Cardinal', 'Founding Engineer', 'Engineering', 'SF (in-person)', '$160K-$235K', '2-5', 'TBD', 'live'),
  ('CollectWise', 'Forward Deployed Engineer', 'Engineering', 'SF (in-person)', 'TBD', 'TBD', 'TBD', 'live'),
  ('CollectWise', 'Founding Account Executive', 'Sales', 'SF (in-person)', 'TBD', 'TBD', 'TBD', 'live'),
  ('CollectWise', 'AI Agent Engineer', 'Engineering', 'SF (in-person)', 'TBD', 'TBD', 'TBD', 'live'),
  ('Colonist', 'Full-Stack Product Developer', 'Engineering', 'Remote', 'TBD', 'TBD', 'TBD', 'live'),
  ('Contrario', 'Member of Technical Staff', 'Engineering', 'SF (in-person)', 'TBD', 'TBD', 'TBD', 'live'),
  ('Convexia', 'Operations Assistant', 'Ops', 'TBD', 'TBD', 'TBD', 'N/A', 'filled'),
  ('DoDo Inc.', 'Customer Support Rep', 'Ops', 'Remote', 'TBD', 'TBD', 'TBD', 'live'),
  ('Dots (YC S21)', 'Head of Growth', 'GTM', 'SF / NYC', 'TBD', 'TBD', 'TBD', 'live'),
  ('Dots (YC S21)', 'Enterprise AE', 'Sales', 'SF / NYC', 'TBD', 'TBD', 'TBD', 'live'),
  ('Dynamo AI', 'Federal Account Executive', 'Sales', 'TBD', 'TBD', 'TBD', 'TBD', 'live'),
  ('foam', 'Founding Engineer', 'Engineering', 'SF (in-person)', '$250K-$400K / 0.25%-2% equity', '3-6', 'TBD', 'live'),
  ('Gallium', 'Content Strategist - LinkedIn', 'GTM', 'Remote US / Remote LATAM', '$60K-$80K / $4K-$6K/mo (LATAM)', 'Flexible', '10%', 'live'),
  ('Gigi', 'Founding CTO', 'Engineering', 'TBD', '$250K-$400K / 5%-10% equity', 'TBD', '18.5%', 'live'),
  ('Gigi', 'Founding Product Designer', 'Design', 'TBD', '$200K-$300K / 1%-3% equity', 'TBD', '17.5%', 'live'),
  ('Innate Inc.', 'Founding Engineer', 'Engineering', 'SF (in-person)', 'TBD', 'TBD', 'TBD', 'live'),
  ('Innate Inc.', 'GTM Lead', 'GTM', 'SF (in-person)', 'TBD', 'TBD', 'TBD', 'live'),
  ('Innate Inc.', 'Chief of Staff', 'Ops', 'SF (in-person)', 'TBD', 'TBD', 'TBD', 'live'),
  ('Jampack AI', 'Integrations Engineer, LATAM', 'Engineering', 'Remote LATAM', '$7K-$10K/mo', '6-8', '10%', 'live'),
  ('Jampack AI', 'Founding Full Stack Engineer', 'Engineering', 'Brooklyn NYC (in-person)', '$160K-$220K / 0.1%-0.5% equity', '2-5', '16.5%', 'live'),
  ('Judgment Labs', 'Forward Deployed AI Engineer', 'Engineering', 'SF (in-person)', '$200K-$400K', 'TBD', 'TBD', 'live'),
  ('Known', 'Strategy & Operations Fellow', 'Ops', 'SF (in-person)', 'TBD', '1-4', 'TBD', 'live'),
  ('Known', 'ML Engineer, Matchmaking', 'Data / ML', 'SF (in-person)', 'TBD', 'TBD', 'TBD', 'live'),
  ('Known', 'Product Engineer, Mobile', 'Engineering', 'SF (in-person)', '$170K-$230K + equity', '2-6', 'TBD', 'live'),
  ('Kobalt Labs', 'Founding Full Stack Engineer', 'Engineering', 'NYC (in-person)', '$200K-$250K / 0.5%-1% equity', '4-7', 'TBD', 'live'),
  ('Kobalt Labs', 'Account Executive (x3)', 'Sales', 'NYC (in-person)', 'TBD', 'TBD', 'TBD', 'live'),
  ('Liquid', 'Growth Marketer', 'GTM', 'NYC (in-person)', '$140K-$180K / 0.2%-0.4% equity', 'TBD', 'TBD', 'live'),
  ('Liquid', 'Product Designer', 'Design', 'NYC (in-person)', '$140K-$180K / 0.1%-0.3% equity', 'TBD', 'TBD', 'live'),
  ('Listen Labs', 'Lead GTM Engineer', 'GTM', 'SF / NYC', '$140K-$210K', '3-7', 'TBD', 'live'),
  ('Listen Labs', 'Growth Operations Lead', 'GTM', 'SF / NYC', 'TBD', 'TBD', 'TBD', 'live'),
  ('Loop AI', 'Staff Engineer', 'Engineering', 'SF (in-person)', 'TBD', '6+', 'TBD', 'live'),
  ('Mason AI', 'Founding Engineer', 'Engineering', 'NYC (in-person)', '$150K-$190K / 1%-2% equity', '2-5', '16.5%', 'live'),
  ('Maximor AI', 'Full Stack Engineer, India', 'Engineering', 'Remote India', '60-80L INR/yr', '3-5', '18%', 'live'),
  ('Maximor AI', 'Full Stack Engineer, LATAM', 'Engineering', 'Remote LATAM', '$10K-$12K/mo', '6-10', '18%', 'live'),
  ('Mem0', 'Full Stack Engineer', 'Engineering', 'SF (in-person)', '$180K-$250K / 0.1%-0.4% equity', 'TBD', '16.5%', 'live'),
  ('Mem0', 'Head of Growth', 'GTM', 'SF (in-person)', 'TBD', 'TBD', 'TBD', 'live'),
  ('Mem0', 'Backend Engineer', 'Engineering', 'SF (in-person)', 'TBD', 'TBD', 'TBD', 'live'),
  ('Mixed Nuts Inc.', 'Buyer, Inventory & Import Specialist', 'Ops', 'Pico Rivera, CA', '$75K-$90K', '2-4', '14.5%', 'live'),
  ('Porter', 'Design / Micro-Interaction Engineer', 'Design', 'NYC (in-person)', '$200K-$280K + equity', '5+', '18%', 'live'),
  ('Porter', 'Kubernetes & Cloud Engineer', 'Engineering', 'NYC (in-person)', 'TBD', 'TBD', '18%', 'live'),
  ('Porter', 'Senior Backend Engineer', 'Engineering', 'NYC (in-person)', 'TBD', 'TBD', '18%', 'live'),
  ('Remy AI', 'Senior Full Stack Engineer, LATAM', 'Engineering', 'Remote LATAM', '$8K-$10K/mo + equity', '5+', 'TBD', 'live'),
  ('Sieve', 'Research Engineer, Computer Vision', 'Data / ML', 'SF (in-person)', 'TBD', 'TBD', 'TBD', 'live'),
  ('Sieve', 'Data Operations Lead', 'Ops', 'SF (in-person)', 'TBD', 'TBD', 'TBD', 'live'),
  ('Simula', 'Senior Mobile SDK Engineer', 'Engineering', 'Remote LATAM', 'TBD', 'TBD', 'TBD', 'live'),
  ('Simula', 'HTML5 Mini Game Developer', 'Engineering', 'Remote LATAM', 'TBD', 'TBD', 'TBD', 'live'),
  ('Soff (YC)', 'Founding AI PM', 'Ops', 'SF (in-person)', 'TBD', 'TBD', 'TBD', 'live'),
  ('Soff (YC)', 'Backend AI Engineer', 'Engineering', 'SF (in-person)', 'TBD', 'TBD', 'TBD', 'live'),
  ('Sphinx Labs', 'Head of Sales', 'Sales', 'SF (in-person)', '$160K-$250K / 0.20%-0.50% equity', '3+', 'TBD', 'live'),
  ('Sphinx Labs', 'Member of Technical Staff', 'Engineering', 'TBD', 'TBD', 'TBD', 'TBD', 'live'),
  ('Strala', 'Sales Development Representative', 'Sales', 'SF (in-person)', 'TBD', 'TBD', '16.5%', 'live'),
  ('Strala', 'Software Engineer', 'Engineering', 'SF (in-person)', 'TBD', 'TBD', '16.5%', 'live'),
  ('Strala', 'Growth', 'GTM', 'SF (in-person)', '$130K-$190K + equity', '0-5', '16.5%', 'live'),
  ('Trellis AI', 'Technical Deployment Strategist', 'Engineering', 'SF (in-person)', 'TBD', 'TBD', 'TBD', 'live'),
  ('Trellis AI', 'Backend AI Engineer', 'Engineering', 'SF (in-person)', 'TBD', 'TBD', 'TBD', 'live'),
  ('TriFetch', 'Founding Sales', 'Sales', 'SF (in-person)', '$150K-$250K base / $300K-$500K OTE', '3-8', '16.5%', 'live'),
  ('Uncountable', 'AI Full-Stack Engineer', 'Engineering', 'TBD', '$130K-$175K + equity', 'TBD', 'TBD', 'live'),
  ('Verita AI', 'Strategic Projects Lead', 'Ops', 'SF (in-person)', '$130K-$160K + equity', '2-5', 'TBD', 'live'),
  ('Verita AI', 'Full Stack Engineer, LATAM', 'Engineering', 'Remote LATAM', 'TBD', 'TBD', 'TBD', 'live'),
  ('VRChat', 'Recommendations Engineer', 'Data / ML', 'Remote US/Canada', '$110K-$150K + equity', '2-6', '17%', 'live'),
  ('Wildcard', 'Full Stack Engineer, LATAM', 'Engineering', 'Remote LATAM', '$7K-$9K/mo', '1.5-5', '10%', 'live'),
  ('Wildcard', 'Founding Engineer', 'Engineering', 'SF (in-person)', '$160K-$200K', 'TBD', 'TBD', 'live'),
  ('Wispr AI', 'LATAM iOS Engineer', 'Engineering', 'Remote LATAM', 'TBD', 'TBD', 'TBD', 'live'),
  ('Wispr AI', 'Growth Engineer', 'Engineering', 'SF (in-person)', 'TBD', 'TBD', 'TBD', 'live')
) as v(c, r, t, l, cm, y, b, s);

-- ── Knowledge base pre-seeds ────────────────────────
insert into knowledge_base (title, category, content, tags, pinned) values
  ('Intro Email Format', 'template', E'## Subject\nName (Role) <> Company Intro\n\n## Body\n(fill in template here)', array['email','template'], true),
  ('Follow-Up Cadence Rules', 'process', E'- FU1 (3 biz days): same thread, same CCs\n- FU2 (6 biz days): same thread, same CCs\n- FU3 (9 biz days): NEW thread, subject "note re: company", under 70 words, flip the ask', array['followup','process'], true),
  ('JD Template — 13 Sections', 'template', E'(fill in the 13-section template)', array['jd','template'], true),
  ('Outreach Rules — No Company Name', 'process', '(fill in rules)', array['outreach'], false),
  ('Ashby Pipeline Stages', 'tool_guide', '(fill in Ashby stage definitions)', array['ashby','ats'], false),
  ('Client Response SLA', 'process', '(fill in SLA rules)', array['client','sla'], false),
  ('Candidate Status Definitions', 'reference', '(fill in definitions)', array['reference'], false),
  ('ATS Archiving vs Rejecting', 'faq', '(fill in)', array['ats','faq'], false),
  ('n8n Automation Inventory', 'tool_guide', '(list all n8n automations)', array['n8n','automation'], false),
  ('Comp Benchmarks by Role Type', 'reference', '(fill in benchmarks)', array['comp','reference'], false);

-- ── Initial KPI entry ───────────────────────────────
insert into kpi_entries (date, period, active_clients, active_roles, notes) values
  (current_date, 'daily', 46, 88, 'Initial seed from v3 migration');

commit;
